### PR TITLE
Fixes #5: Checking for application focus before tokenizing editor

### LINKED ISSUE #5: Uncaught TypeError: Cannot read property 'id' of null
[Enter steps to reproduce below:]
1. unsure

**Atom Version**: 1.8.0
**System**: Ubuntu 14.04.4
**Thrown From**: [autocomplete-java-minus](https://github.com/noseglid/autocomplete-java-minus) package, v0.12.0
### Stack Trace

Uncaught TypeError: Cannot read property 'id' of null

```
At /home/quincy/.atom/packages/autocomplete-java-minus/lib/editor-tokens.js:70

TypeError: Cannot read property 'id' of null
    at EditorTokens.refreshTokens (/home/quincy/.atom/packages/autocomplete-java-minus/lib/editor-tokens.js:70:39)
    at /home/quincy/.atom/packages/autocomplete-java-minus/lib/editor-tokens.js:78:12
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1378:25
```
### Commands

```
     -0:20.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:15.6.0 pane:show-previous-item (ol.results-view.list-tree.focusable-panel.has-collapsable-children)
  2x -0:11.4.0 core:move-down (atom-text-editor.editor.power-mode.is-focused)
     -0:10.6.0 editor:newline (atom-text-editor.editor.power-mode.is-focused)
  2x -0:09.7.0 core:backspace (atom-text-editor.editor.power-mode.is-focused)
     -0:09.1.0 core:move-up (atom-text-editor.editor.power-mode.is-focused)
     -0:08.9.0 editor:newline (atom-text-editor.editor.power-mode.is-focused)
     -0:06.1.0 core:backspace (atom-text-editor.editor.power-mode.is-focused)
     -0:05.1.0 core:save (atom-text-editor.editor.power-mode.is-focused)
     -0:04.2.0 core:move-left (atom-text-editor.editor.power-mode.is-focused)
     -0:03.9.0 java-importer:import (atom-text-editor.editor.power-mode.is-focused)
     -0:03.0 core:move-up (atom-text-editor.editor.power-mode.is-focused)
     -0:02.6.0 core:move-left (atom-text-editor.editor.power-mode.is-focused)
     -0:02.3.0 editor:newline (atom-text-editor.editor.power-mode.is-focused)
     -0:02.0 core:paste (atom-text-editor.editor.power-mode.is-focused)
     -0:01.8.0 core:save (atom-text-editor.editor.power-mode.is-focused)
```
### Config

``` json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      "*.class"
    ],
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
activate-power-mode, v0.7.0
atom-material-syntax, v0.4.6
atom-material-ui, v1.2.13
autocomplete-java-minus, v0.12.0
busy, v0.5.0
color-tabs, v0.1.8
java-classpath-registry, v0.4.0
java-import-wiz, v0.5.0
java-importer, v1.4.1
language-gradle, v0.0.3
language-groovy, v0.6.0
linter, v1.11.14
linter-javac, v1.9.4
merge-conflicts, v1.4.4

# Dev
No dev packages
```

### PR DESCRIPTION
**Pull request by jfs**
This should address issue #5. There is a 300ms delay before `onDidStopChanging` is called. In this time it is possible for the application to lose focus. This causes the package to throw an `Uncaught TypeError`. Worse it puts the package into a state where `awaitingTokens` get's stuck at `true` and the editor will not be tokenized until restart.

### CODE REVIEW

**Comment by jfs** [comment]
@noseglid Is there an issue with this fix or have you just not had a chance to check it yet?

**Comment by noseglid** [comment]
I have not had time yet. I will look at this as soon as possible.

File: lib/editor-tokens.js [hunk 1]
```diff
@@ -53,19 +53,23 @@ class EditorTokens {
...
       // Not loaded. Java grammar possibly not installed. Skip refreshing.
       return;
     }
+    const focusedWindow = remote.BrowserWindow.getFocusedWindow();
+    if (!focusedWindow) {
+      // Lost focus. Skip refreshing.
+      return;
+    }
 
+    this.awaitingTokens = true;
```
Comment (jfs) [inline lib/editor-tokens.js:67]: One thing to note here is I moved `this.awaitingToken = true;` below the consistency checks because if either failed then we'd get stuck with a true value and stop tokenizing until there was a restart.

**Comment by noseglid** [comment]
Thank you for your patience. I have been quite busy lately.
I have merged this and made a new release. Thank you for the contribution!

**Comment by jfs** [comment]
No problem. Glad to help.
